#!/usr/bin/env bash
# One-command deploy to Fly.io + Neon.
#
# Before running:
#   1. fly auth login          (browser; the Fly account must have a confirmed payment method)
#   2. Copy the Neon connection string to your clipboard:
#      Neon console -> project "agentbridge" -> Connect -> copy the psql/URI string
#
# The connection string is read from the clipboard and passed straight to Fly.
# It is never printed, never written to a file, and never pasted into a chat.
set -euo pipefail

GATEWAY_APP="${GATEWAY_APP:-agentbridge-gateway}"
ORDERS_APP="${ORDERS_APP:-agentbridge-orders}"
REGION="${REGION:-sin}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYFILE="$HERE/deploy/.generated-keys.env"

step() { printf '\n\033[1m== %s\033[0m\n' "$1"; }
die() { echo "FAIL: $1" >&2; exit 1; }

command -v fly >/dev/null || die "flyctl is not installed (brew install flyctl)"
fly auth whoami >/dev/null 2>&1 || die "not logged in — run: fly auth login"

step "Reading the Neon connection string from the clipboard"
RAW="$(pbpaste)"
[[ "$RAW" == postgres* ]] || die "the clipboard does not hold a postgres:// connection string"

# Split the URI without ever echoing it.
eval "$(python3 - <<'PY'
import os, shlex, subprocess, urllib.parse
raw = subprocess.run(["pbpaste"], capture_output=True, text=True).stdout.strip()
raw = raw.removeprefix("psql ").strip().strip("'\"")
u = urllib.parse.urlparse(raw)
host = u.hostname or ""
db = (u.path or "/").lstrip("/") or "neondb"
jdbc = f"jdbc:postgresql://{host}/{db}?sslmode=require"
print("DB_JDBC=" + shlex.quote(jdbc))
print("DB_USER=" + shlex.quote(urllib.parse.unquote(u.username or "")))
print("DB_PASSWORD=" + shlex.quote(urllib.parse.unquote(u.password or "")))
print("DB_HOST=" + shlex.quote(host))
PY
)"
[[ -n "${DB_HOST:-}" && -n "${DB_PASSWORD:-}" ]] || die "could not parse the connection string"
echo "host: $DB_HOST (password not shown)"

step "Creating the apps if they do not exist"
fly apps list 2>/dev/null | grep -q "^$ORDERS_APP " || fly apps create "$ORDERS_APP" --org personal
fly apps list 2>/dev/null | grep -q "^$GATEWAY_APP " || fly apps create "$GATEWAY_APP" --org personal

step "Generating API keys"
# Written to a git-ignored file rather than the terminal, so the secrets do not end
# up in scrollback or in any log that scrollback is pasted into.
newkey() { echo "ab_$(openssl rand -base64 32 | tr -d '/+=' | head -c 43)"; }
if [[ -f "$KEYFILE" ]]; then
  echo "reusing the keys already in deploy/.generated-keys.env"
  # shellcheck disable=SC1090
  source "$KEYFILE"
else
  ADMIN_KEY="$(newkey)"; GUEST_KEY="$(newkey)"
  umask 077
  cat > "$KEYFILE" <<EOF
# Generated by scripts/deploy_fly.sh. Git-ignored. Keep it or lose access.
ADMIN_KEY=$ADMIN_KEY
GUEST_KEY=$GUEST_KEY
EOF
  echo "written to deploy/.generated-keys.env"
fi

step "Setting secrets"
fly secrets set -a "$ORDERS_APP" --stage \
  ORDERS_DB_URL="$DB_JDBC" ORDERS_DB_USER="$DB_USER" ORDERS_DB_PASSWORD="$DB_PASSWORD" >/dev/null
fly secrets set -a "$GATEWAY_APP" --stage \
  GATEWAY_DB_URL="$DB_JDBC" GATEWAY_DB_USER="$DB_USER" GATEWAY_DB_PASSWORD="$DB_PASSWORD" \
  AGENTBRIDGE_ADMIN_KEY="$ADMIN_KEY" AGENTBRIDGE_GUEST_KEY="$GUEST_KEY" >/dev/null
echo "staged for both apps"

step "Deploying the upstream"
fly deploy -c deploy/fly/orders.fly.toml --remote-only --wait-timeout 600

step "Deploying the gateway"
fly deploy -c deploy/fly/gateway.fly.toml --remote-only --wait-timeout 600

step "Verifying"
URL="https://$GATEWAY_APP.fly.dev"
for _ in $(seq 1 30); do
  if curl -fsS "$URL/api/v1/info" >/dev/null 2>&1; then break; fi
  sleep 5
done
curl -fsS "$URL/api/v1/info" | python3 -m json.tool || die "the gateway did not answer at $URL"

echo
echo "Tools visible to the guest key:"
curl -fsS "$URL/api/v1/tools" -H "Authorization: Bearer $GUEST_KEY" \
  | python3 -c 'import json,sys; [print("  " + t["name"].ljust(26) + t["requiredScope"]) for t in json.load(sys.stdin)]'

printf '\n\033[1mDeployed: %s\033[0m\n' "$URL"
echo "MCP endpoint: $URL/mcp   (send Authorization: Bearer <key>)"
echo "Keys are in deploy/.generated-keys.env — not in this output, and not in git."
